---
- hosts: all
  become: true
  become_method: sudo
  remote_user: ubuntu

  # Variables declartion for the playbook file
  vars:
    NODEJS_VERSION: 10
    PM2_PATH: $PATH:/usr/bin /usr/lib/node_modules/pm2/bin/pm2 startup systemd -u ubuntu --hp /home/ubuntu
    PROJECT_FOLDER_PATH: /home/ubuntu/neon-ah
    SITES_AVAILABLE: /etc/nginx/sites-available
    SITES_ENABLED: /etc/nginx/sites-enabled
    SITES_AVAILABLE_AH: /etc/nginx/sites-available/ah
    SITES_ENABLED_AH: /etc/nginx/sites-enabled/ah

  tasks:
    # Update the Cache
    - name: Update cache
      apt:
        update_cache: yes

    # Add the gpd key for Node.JS to the instance
    - name: Add gpg key for NodeJS LTS
      apt_key:
        url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
        state: present

    # Add the Node.JS repo to the list of packages repo on the instance
    - name: Install NodeJS Repo
      apt_repository:
        repo: "deb https://deb.nodesource.com/node_{{ NODEJS_VERSION }}.x {{ ansible_distribution_release }} main"
        state: present
        update_cache: yes

    # Install the Node.JS package on the instance
    - name: Install Node.JS
      apt:
        name: nodejs
        state: present

    # Add the gpd key for Yarn package to the instance
    - name: Add gpg key for Yarn
      apt_key:
        url: "https://dl.yarnpkg.com/debian/pubkey.gpg"
        state: present 

    # Add the Yarn package repo to the list of packages repo on the instance  
    - name: Install Yarn Repo
      apt_repository:
        repo: "deb https://dl.yarnpkg.com/debian stable main"
        state: present
        update_cache: yes

    # Install the Yarn package on the instance
    - name: Install Yarn
      apt:
        name: yarn
        state: present

    # Clone the React project repo from GitHub on the instance
    - name: Clone Project Repository from GitHub
      shell: git clone -b aws-deploy https://github.com/andela/neon-ah-frontend.git neon-ah


    # Use Yarn to install the project dependencies
    - name: Install the Project dependencies
      shell: yarn install
      args:
        chdir: "{{ PROJECT_FOLDER_PATH }}"

    # Run the command specified for bundling the project with Webpack for production
    - name: Use Webpack to bundle the project for production
      shell: yarn run heroku-postbuild
      args:
        chdir: "{{ PROJECT_FOLDER_PATH }}"

    # Install Nginx server
    - name: Install Nginx
      apt:
        name: nginx
        state: latest

    # Remove the default configuration files for Nginx
    - name: Remove Nginx default config files
      shell: |
        cd {{ SITES_AVAILABLE }}
        rm default

        cd {{ SITES_ENABLED }}
        rm default

    # Setup Nginx for reverse proxy to the Node app server
    - name: Configure Nginx for Reverse Proxy
      shell: echo "server  {
            listen 80;
            location / {
              proxy_pass http://127.0.0.1:3110;
            }
          }" >> {{ SITES_AVAILABLE_AH }}

    # Symlink the new Nginx configuration files
    - name: Symlink sites-available file with sites-enabled
      shell: |
        ln -s {{ SITES_AVAILABLE_AH }} {{ SITES_ENABLED_AH }}

    # Start the Nginx server
    - name: Start Nginx
      service: 
        name: nginx
        state: started

    # Add pm2 package
    - name: Install pm2 to run app in the background
      shell: npm install pm2 -g

    # Add an app start script command for pm2
    - name: Add pm2 start script
      shell: |
        cd /home/ubuntu/neon-ah
        echo '
          {
            "apps": [
              {
                "name": "Team Neon Authors Haven",
                "script": "npm",
                "args": "run start"
              }
            ]
          }
        ' > app_start.config.json
    
    # Start the app with pm2 and make it run in the background
    - name: Start node app with pm2
      shell: |
        cd /home/ubuntu/neon-ah
        sudo pm2 start ./app_start.config.json
        sleep 30
        sudo pm2 startup
        sudo env PATH={{PM2_PATH}}
        sudo pm2 save

